---
title: "cube scrambler"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pheatmap)
library(tidyverse)
```

```{r define stuff}

CW<-function(face){
  faceDV<-face
  face[1,1]<-faceDV[3,1]
  face[1,2]<-faceDV[2,1]
  face[1,3]<-faceDV[1,1]
  face[2,1]<-faceDV[3,2]    
  face[2,3]<-faceDV[1,2]
  face[3,1]<-faceDV[3,3]
  face[3,2]<-faceDV[2,3]
  face[3,3]<-faceDV[1,3]
  return(face)
} # Clockwise rotation of a 3x3 face
CCW<-function(face){
  face<-CW(CW(CW(face)))
  return(face)
} # Counterclockwise rotation of a 3x3 face

X<-function(cube){
  cubeDV<-cube
  
  up<-cube[1:3, 4:6] #
  left<-cube[4:6, 1:3]             #
  front<-cube[4:6, 4:6] #
  right<-cube[4:6, 7:9]            #
  back<-cube[4:6, 10:12] #
  down<-cube[7:9, 4:6]             #
  
  cube[1:3, 4:6]<-front #up
  cube[4:6, 1:3]<-CCW(left)         #left
  cube[4:6, 4:6]<-down # front
  cube[4:6, 7:9]<-CW(right)         # right
  cube[4:6, 10:12]<-CW(CW(up)) # back
  cube[7:9, 4:6]<-CW(CW(back))      #down
  
  return(cube)
} # rotate cube 90 degrees CW on X axis
Xp<-function(cube){
  return(X(X(X(cube))))
} # rotate cube 90 degrees CCW on X axis
Y<-function(cube){
  cubeDV<-cube
  
  up<-cube[1:3, 4:6]
  left<-cube[4:6, 1:3]
  front<-cube[4:6, 4:6]
  right<-cube[4:6, 7:9]
  back<-cube[4:6, 10:12]
  down<-cube[7:9, 4:6]
  
  cube[1:3, 4:6]<-CW(up)
  cube[4:6, 1:3]<-front
  cube[4:6, 4:6]<-right
  cube[4:6, 7:9]<-back
  cube[4:6, 10:12]<-left
  cube[7:9, 4:6]<-CCW(down)
  
  return(cube)
} # rotate cube 90 degrees CW on Y axis
Yp<-function(cube){
  return(Y(Y(Y(cube))))
} # rotate cube 90 degrees CCW on Y axis
Z<-function(cube){
  cubeDV<-cube
  
  up<-cube[1:3, 4:6]
  left<-cube[4:6, 1:3]
  front<-cube[4:6, 4:6]
  right<-cube[4:6, 7:9]
  back<-cube[4:6, 10:12]
  down<-cube[7:9, 4:6]
  
  cube[1:3, 4:6]<-CW(left)
  cube[4:6, 1:3]<-CW(down)
  cube[4:6, 4:6]<-CW(front)
  cube[4:6, 7:9]<-CW(up)
  cube[4:6, 10:12]<-CCW(back)
  cube[7:9, 4:6]<-CW(right)
  
  return(cube)
} # rotate cube 90 degrees CW on Z axis
Zp<-function(cube){
  return(Z(Z(Z(cube))))
} # rotate cube 90 degrees CCW on Z axis

Turn_CW<-function(cube){
  cubeDV<-cube
  
  up<-cube[1:3, 4:6]
  left<-leftDV<-cube[4:6, 1:3]
  front<-frontDV<-cube[4:6, 4:6]
  right<-rightDV<-cube[4:6, 7:9]
  back<-backDV<-cube[4:6, 10:12]
  
  left[1,]<-frontDV[1,]
  front[1,]<-rightDV[1,]
  right[1,]<-backDV[1,]
  back[1,]<-leftDV[1,]
  
  cube[1:3, 4:6]<-CW(up)
  cube[4:6, 1:3]<-left
  cube[4:6, 4:6]<-front
  cube[4:6, 7:9]<-right
  cube[4:6, 10:12]<-back
  
  return(cube)
} # preform a U move
Turn_CCW<-function(cube){
  
  return(Turn_CW(Turn_CW(Turn_CW(cube))))
} # preform a U' move

scrambler<-function(n){
moves<-matrix(c("R", "R'", "l", "l'", "R2",
                "L", "L'", "r", "r'", "L2",
                "U", "U'", "d", "d'", "U2",
                "D", "D'", "u", "u'", "D2",
                "F", "F'", "b", "b'", "F2",
                "B", "B'", "f", "f'", "B2",
                "M", "M'", "z", "z'", "M2",
                "x", "x'", "y", "y'", "y"), nrow=8, byrow=T)
dv1<-sample(1:8, 1)
scram<-c()
for(i in 1:n){
  scram<-c(scram, moves[dv1, sample(1:5,1)])
  dv2<-1:8 ; dv2<-dv2[-dv1]
  dv1<-sample(dv2, 1)
} # ensures no redundant moves; (R', R) is impossible
return(noquote(scram))
} # generates a random scramble with n moves. can adjust moveset here

gif<-function(fps, title="gif"){
  ## list file names and read in
imgs <- list.files("/Users/nicklatina/Desktop/cube", full.names = T)
imgs<-imgs[order(imgs)]
img_list <- lapply(imgs, image_read)

## join the images together
img_joined <- image_join(img_list)

## animate at 2 frames per second
img_animated <- image_animate(img_joined, fps = fps)

## view animated image
#img_animated

## save to disk
image_write(image = img_animated,
            path = paste("/Users/nicklatina/Desktop/",title,".gif", sep=""))
} #gif maker function
```

```{r create solved cube}

ogcube=matrix(rep(0, 12*9), nrow=9)

UF<-c(0,3) # in a normal matrix for one face[(1,1),(1,2),(1,3),(2,1),(2,2)..etc], The U face will require adding 0 to every row and 3 to every column
LF<-c(3,0)
FF<-c(3,3)
RF<-c(3,6)
BF<-c(3,9)
DF<-c(6,3)
faces<-list(UF,LF,FF,RF,BF,DF)

# Create solved cube
for(C in 1:6){
  for(i in ((1:3) + faces[[C]][1])){
    for(j in ((1:3) + faces[[C]][2])){
      ogcube[i,j]<-C
    }
  }
}

color<-colorRampPalette(c("grey50","white", "orange", "green", "red", "blue", "yellow"))(7)

pheatmap(ogcube+1,
         color = color, border_color="black",
         cluster_rows=FALSE, cluster_cols=FALSE)


```


```{r checkerboard}
cube<-ogcube #resets for easy re-scrambling

scram = c("R2", "L2", "D2", "U2", "F2", "B2")
```


```{r complex checkerboard}
cube<-ogcube #resets for easy re-scrambling

scram =c("U'", "R2", "L2", "F2", "B2", "U'", "R", "L", "F", "B'", "U", "F2", "D2", "R2", "L2", "F2", "U2", "F2", "U'", "F2")
```


```{r superflip}
cube<-ogcube #resets for easy re-scrambling

scram = c("U", "R2", "F", "B", "R", "B2", "R", "U2", "L", "B2", "R", "U'", "D'", "R2", "F", "R'", "L", "B2","U2", "F2")
```


```{r cube-in-a-cube}
cube<-ogcube #resets for easy re-scrambling

scram = c("U'", "L'", "U'", "F'", "R2", "B'", "R", "F", "U", "B2", "U", "B'", "L", "U'", "F", "U", "R", "F'")
```

```{r random scramble}
cube<-ogcube #resets for easy re-scrambling

scram<-scrambler(30)
```

```{r scramble}
for(i in 1:length(scram)){
  DV_cube<-cube
  DV_cube<-matrix(case_when(
    
                  scram[i] == "U" ~ Turn_CW(cube),
                  scram[i] == "U'" ~ Turn_CCW(cube),
                  scram[i] == "D" ~ X(X(Turn_CW(X(X(cube))))),
                  scram[i] == "D'" ~ X(X(Turn_CCW(X(X(cube))))),
                  scram[i] == "R" ~ Z(Turn_CW(Zp(cube))),
                  scram[i] == "R'" ~ Z(Turn_CCW(Zp(cube))),
                  scram[i] == "L" ~ Zp(Turn_CW(Z(cube))),
                  scram[i] == "L'" ~ Zp(Turn_CCW(Z(cube))),
                  scram[i] == "F" ~ Xp(Turn_CW(X(cube))),
                  scram[i] == "F'" ~ Xp(Turn_CCW(X(cube))),
                  scram[i] == "B" ~ X(Turn_CW(Xp(cube))),
                  scram[i] == "B'" ~ X(Turn_CCW(Xp(cube))),
                  scram[i] == "U2" ~ Turn_CW(Turn_CW(cube)),
                  scram[i] == "D2" ~ X(X(Turn_CW(Turn_CW(X(X(cube)))))),
                  scram[i] == "R2" ~ Z(Turn_CW(Turn_CW(Zp(cube)))),
                  scram[i] == "L2" ~ Zp(Turn_CW(Turn_CW(Z(cube)))),
                  scram[i] == "F2" ~ Xp(Turn_CW(Turn_CW(X(cube)))),
                  scram[i] == "B2" ~ X(Turn_CW(Turn_CW(Xp(cube)))),
                  scram[i] == "u" ~ Y(X(X(Turn_CW(X(X(cube)))))),
                  scram[i] == "u'" ~ Yp(X(X(Turn_CCW(X(X(cube)))))),
                  scram[i] == "d" ~ Yp(Turn_CW(cube)),
                  scram[i] == "d'" ~ Y(Turn_CCW(cube)),
                  scram[i] == "r" ~ X(Zp(Turn_CW(Z(cube)))),
                  scram[i] == "r'" ~ Xp(Zp(Turn_CCW(Z(cube)))),
                  scram[i] == "l" ~ Xp(Z(Turn_CW(Zp(cube)))),
                  scram[i] == "l'" ~ X(Z(Turn_CCW(Zp(cube)))),
                  scram[i] == "f" ~ Z(X(Turn_CW(Xp(cube)))),
                  scram[i] == "f'" ~ Zp(X(Turn_CCW(Xp(cube)))),
                  scram[i] == "b" ~ Zp(Xp(Turn_CW(X(cube)))),
                  scram[i] == "b'" ~ Z(Xp(Turn_CCW(X(cube)))),
                  scram[i] == "M" ~ Z(Turn_CW(Zp(Xp(Zp(Turn_CCW(Z(cube))))))),
                  scram[i] == "M'" ~ Z(Turn_CCW(Zp(X(Zp(Turn_CW(Z(cube))))))),
                  scram[i] == "M2" ~ Z(Turn_CCW(Turn_CCW(X(X(Turn_CW(Turn_CW(Z(cube)))))))),
                  scram[i] == "x" ~ X(cube),
                  scram[i] == "x'" ~ X(X(X(cube))),
                  scram[i] == "y" ~ Y(cube),
                  scram[i] == "y'" ~ Y(Y(Y(cube))),
                  scram[i] == "z" ~ Z(cube),
                  scram[i] == "z'" ~ Z(Z(Z(cube))),
                  
                
                  ), nrow=9, byrow=F)
  cube<-DV_cube
}


```

```{r display}
color<-colorRampPalette(c("grey50","white", "orange2", "green3", "red", "blue", "yellow"))(7)# ; show_col(color, labels=F)

noquote(scram)
pheatmap(cube,
         color = color, border_color="black",
         cluster_rows=FALSE, cluster_cols=FALSE,
         legend = F
         )

```


